packages:
  - app
  - cdk/cloudfront
  - cdk/cloudfront/function
  - cdk/kvs

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

overrides:
  seroval@<1.4.1: '>=1.4.1'
  seroval@<=1.4.0: '>=1.4.1'
