packages:
  - app
  - cdk/cloudfront
  - cdk/cloudfront/function
  - cdk/kvs

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver

overrides:
  '@eslint/eslintrc>ajv': ^6.12.4
  ajv@<8.18.0: '>=8.18.0'
  eslint>ajv: ^6.12.4
  seroval@<1.4.1: '>=1.4.1'
