name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        node-version: [20.x]

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: pnpm/action-setup@v4
      name: Install pnpm
      id: pnpm-install
      with:
        version: latest
        run_install: |
          - recursive: true
            cwd: cdk
            args: [--no-frozen-lockfile]

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        check-latest: true

    - name: Build (cdk)
      working-directory: ./cdk
      run: pnpm lint && pnpm -r build

    - name: Install dependencies
      working-directory: ./app
      run: pnpm install

    - name: Build (app)
      working-directory: ./app
      run: pnpm lint && pnpm -r build
