name: Deploy

on:
  push:
    branches:
    - main

  workflow_dispatch:

env:
  OIDC_IAM_ROLE_ARN: ${{ secrets.OIDC_IAM_ROLE_ARN }}
  AWS_REGION: us-west-2

permissions:
  id-token: write
  contents: read

# 同時実行すると CREATE_IN_PROGRESS や UPDATE_IN_PROGRESS 状態で cdk deploy を行う可能性があるため抑止する
concurrency:
  group: "cloudformation"
  cancel-in-progress: false

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false

    - name: Install pnpm
      uses: pnpm/setup@5d160c5bc68a09337ad0d5654e237e03253b5879 # v1.0.0

    - name: Install AWS CLI
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
        rm -rf awscliv2.zip aws

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@254c19bd240aabef8777f48595e9d2d7b972184b # v6.2.1
      with:
        role-to-assume: ${{ env.OIDC_IAM_ROLE_ARN }}
        role-session-name: GitHubActions
        aws-region: ${{ env.AWS_REGION }}

    - name: deploy (kvs)
      working-directory: ./cdk/kvs
      run: pnx aws-cdk@latest deploy

    - name: Retirives KVS ARN and ID
      id: kvs-arn-id
      run: |
        ARN=$(aws cloudformation describe-stacks --stack-name cloudfront-kvs-example-kvs-stack --query 'Stacks[].Outputs[?OutputKey==`KvsArn`].OutputValue' --no-cli-pager --output text)
        ID=$(aws cloudformation describe-stacks --stack-name cloudfront-kvs-example-kvs-stack --query 'Stacks[].Outputs[?OutputKey==`KvsId`].OutputValue' --no-cli-pager --output text)
        echo "ARN=${ARN}" >> $GITHUB_OUTPUT
        echo "ID=${ID}" >> $GITHUB_OUTPUT

    - name: deploy (cloudfront)
      working-directory: cdk/cloudfront
      run: pnx aws-cdk@latest deploy -c kvs-arn=${{ steps.kvs-arn-id.outputs.ARN }} -c kvs-id=${{ steps.kvs-arn-id.outputs.ID }}
